# Generated by Django 4.1.5 on 2023-01-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialPlatforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
