# Generated by Django 4.1.5 on 2023-01-23 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialPlatforms', '0002_social_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedsocial',
            name='token_url',
            field=models.CharField(default=datetime.datetime(2023, 1, 23, 0, 57, 35, 56371, tzinfo=datetime.timezone.utc), max_length=500),
            preserve_default=False,
        ),
    ]
