# Generated by Django 4.1.5 on 2023-01-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_social'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
