# Generated by Django 4.1.5 on 2023-01-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiktokvideo',
            name='file',
            field=models.FileField(upload_to='videos/tiktok/'),
        ),
    ]
