# Generated by Django 4.1.5 on 2023-01-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0003_alter_tiktokvideo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokvideo',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
