# Generated by Django 4.1.5 on 2023-01-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0006_rename_platform_tiktokvideo_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokvideo',
            name='errors',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
