# Generated by Django 4.1.5 on 2023-01-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.DateTimeField()),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded', models.BooleanField(default=False)),
            ],
        ),
    ]
